apiVersion: v1
kind: ConfigMap
metadata:
  name: consorcio-config
  namespace: consorcio
data:
  KAFKA_BROKERS: "kafka-0.kafka.consorcio.svc.cluster.local:9092"
  KAFKA_GROUP_ID: "consorcio-api"
  AWS_REGION: "us-east-1"
  NODE_ENV: "production"
  PORT: "3000"
  CORS_ORIGINS: "https://app.consorciopro.com.br,https://admin.consorciopro.com.br"
  JWT_EXPIRES_IN: "15m"
  CNPJ_ADMINISTRADORA: "00000000000000"
